apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailhog
  name: mailhog
  namespace: "monitoring"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - image: mailhog/mailhog:v1.0.1
        name: mailhog
        ports:
          - name: http
            containerPort: 8025
          - name: smtp
            containerPort: 1025
