apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8025
    protocol: TCP
    targetPort: 8025
  - name: smtp
    port: 1025
    protocol: TCP
    targetPort: 1025
  selector:
    app: mailhog
status:
  loadBalancer: {}
