---
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

#kubeScheduler:
  #enabled: false

#kubeControllerManager:
  #enabled: false

prometheus:
  ingress:
    enabled: true
    hosts: &prometheus-hosts
      - "prometheus.${DOMAIN}"
    tls:
      - hosts: *prometheus-hosts
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

grafana:
  plugins: ["jdbranham-diagram-panel"]
  persistence:
    enabled: true
  deploymentStrategy:
    type: Recreate
  ingress:
    enabled: true
    hosts: &grafana-hosts
      - "grafana.${DOMAIN}"
    tls:
      - hosts: *grafana-hosts

alertmanager:
  ingress:
    enabled: true
    hosts: &alertmanager-hosts
      - "alertmanager.${DOMAIN}"
    tls:
      - hosts: *alertmanager-hosts
  config:
    route:
      routes: []
      receiver: 'exploit-team-by-email'
    receivers:
      - name: 'null'
      - name: "exploit-team-by-email"
        email_configs:
          - to: 'my-team@exploit.fr'
            from: 'a-team@prometheus.fr'
            smarthost: 'mailhog.monitoring:1025'
            require_tls: false
